[package]
distribution = "2201.9.3"
org = "ballerinax"
name = "openai.audio"
version = "2.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI/Audio", "OpenAI", "Cost/Paid", "speech-to-text", "Whisper", "Vendor/OpenAI"] 
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.audio"

[build-options]
observabilityIncluded = true